#!/bin/sh
# Wiki push

wikiFolder="YT.wiki"
wikiStatus=$(git status ./$wikiFolder --porcelain)
Yellow='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

if [ -e ./$wikiFolder ]
then
  if [[ "$wikiStatus" = *"M $wikiFolder"* ]]
  then
  echo -e "${RED}Wiki has changed. Please commit and push the changes from Wiki repository - $wikiFolder ${NC}"
  exit 1
  fi
else
  echo -e "${Yellow}Wiki page is absent in your local repository${NC}"
fi

