#!/bin/sh
# Wiki push

wikiFolder="YT.wiki"
wikiStatus=$(git status ./$wikiFolder --porcelain)


if [ ! -d "./$wikiFolder" ] || [ -z "$(ls -A ./$wikiFolder)" ]
then
  echo
  echo "Wiki submodule is absent in your local repository"
  echo
elif [[ "$wikiStatus" = *"M $wikiFolder"* ]]
  then
  echo
  echo "Wiki has changed. Please commit and push the changes from Wiki submodule - $wikiFolder/"
  echo "After the pushing please commit the changes in main repository (git add $wikiFolder && git commit -m <message> && git push)"
  echo
  exit 1
fi

