#!/bin/sh
# Run linting tasks and prevent push in case of errors

echo "Push wiki pages"
cd ../YT.wiki/
echo "Pushing wiki pages"
git add . && git push && exit 0 || echo "Can not push wiki pages" exit 1
